# Generated by Django 2.2 on 2019-11-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-updated',), 'permissions': (('assign_task', 'Assign task'),), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
