# Generated by Django 2.2 on 2019-11-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_auto_20191105_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-updated',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
