# Generated by Django 2.2 on 2019-11-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_auto_20191106_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('-updated',), 'permissions': (('update_project', 'Update project'),), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectmanagers',
            options={'verbose_name': 'Участник проекта', 'verbose_name_plural': 'Участники проекта'},
        ),
    ]
