# Generated by Django 2.2 on 2019-11-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_auto_20191106_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('-updated',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
