# Generated by Django 2.2 on 2019-11-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'default_permissions': 'change', 'ordering': ['-date_joined'], 'permissions': (('can_change', 'Can change'),), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'users'},
        ),
    ]
