# Generated by Django 2.2.6 on 2019-10-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
